name: "Build_push_sunav2_ucrt_group"

on:
  push:
    branches:
      - 'master'
    paths:
      - 'modules_combined/sunav2_ucrt_group/**'
      - 'modules/filter_joiner/**'
      - 'modules/common/**'
      - 'flow/flow.sunav2.exp.uncert/**'
      - 'flow/flow.insufficient.data/**'
  workflow_dispatch: {} # Allows trigger of workflow from web interface

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
  # Use github and google registries
  GHCR_REGISTRY: ghcr.io
  GCP_ARTIFACT_HOST: ${{ vars.SHARED_WIF_LOCATON }}-docker.pkg.dev
  GCP_REGISTRY: ${{ vars.SHARED_WIF_LOCATON }}-docker.pkg.dev/${{ vars.SHARED_WIF_PROJECT }}/${{ vars.SHARED_WIF_REPO }}
  GCP_PROVIDER:  ${{ vars.SHARED_WIF_PROVIDER }}
  GCP_SERVICE_ACCOUNT: ${{ vars.SHARED_WIF_SERVICE_ACCOUNT }}
  GHCR_NS: battelleecology
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # Get just the repo name from the event, i.e., NEON-IS-data-processing
  REPO_NAME: ${{ github.event.repository.name }}
  # IS module name
  MODULE_PATH: ./modules_combined/sunav2_ucrt_group
  IMAGE_NAME: neon-is-sunav2-ucrt-group

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
        contents: 'write'
        id-token: 'write'
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4.1.4"
        with:
          fetch-depth: '0'

      - name: Get short SHA
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push
        uses: ./.github/actions/build-push
        with:
            image-tag: "${short_sha}"
            