name: "Build-push-update_flow.troll.baro.conv"

on:
  push:
    tags:
      - "flow.troll.baro.conv/v*.*.*"
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Use github and google registries
  GHCR_REGISTRY: ghcr.io
  # GHCR_NS, i.e, NEONSciene, in lowercase
  # GHCR_NS: ${{ github.repository_owner }}
  GHCR_NS: ${{ vars.SHARED_WIF_REPO }}
  GCP_ARTIFACT_HOST: ${{ vars.SHARED_WIF_LOCATON }}-docker.pkg.dev
  GCP_REGISTRY: ${{ vars.SHARED_WIF_LOCATON }}-docker.pkg.dev/${{ vars.SHARED_WIF_PROJECT }}/${{ vars.SHARED_WIF_REPO }}
  GCP_PROVIDER:  ${{ vars.SHARED_WIF_PROVIDER }}
  GCP_SERVICE_ACCOUNT: ${{ vars.SHARED_WIF_SERVICE_ACCOUNT }}
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # Get just the repo name from the event, i.e., NEON-IS-data-processing, in lowercase
  # REPO_NAME: ${{ github.event.repository.name }}
  REPO_NAME: neon-is-data-processing
  # IS module name
  MODULE_PATH: ./flow/flow.troll.baro.conv
  IMAGE_NAME: neon-is-troll-baro-conv

jobs:
  build-push-update:
    runs-on: ubuntu-latest
    permissions:
        contents: 'write'
        security-events: write
        packages: write
        id-token: 'write'
        pull-requests: 'write'

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4.1.4"
        with:
          ref: 'master'
          fetch-depth: '0'

      - name: Get short SHA
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get semver
        run:  echo "semver=$(git describe --tags --abbrev=0 --match=flow.troll.baro.conv/v*.*.* | awk -F "/" '{print $2}')" >> $GITHUB_ENV 

      - name: Build push and update
        uses: ./.github/actions/build-push-update
