name: "Run modules unit tests"

on:
  push:
    branches:
      - master
    paths:
      - modules/**
  workflow_dispatch: {} # Allows trigger of workflow from web interface

jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.10
          cache: pip
          cache-dependency-path: modules/requirements.txt

      - name: Install Dependencies
        run: pip install -r modules/requirements.txt coverage

      - name: Run Tests
        run: |
          cd modules
          coverage run -m pytest
          coverage xml

      - name: Generate Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: modules/coverage.xml
          badge: true
          format: markdown
          output: file

      - name: Add Coverage to Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
